/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/invoices": {
    /** List invoices */
    get: {
      parameters: {
        query: {
          tenant_id: string;
          status?: "open" | "paid" | "disputed";
          cursor?: string;
        };
      };
      responses: {
        /** @description Paginated invoices */
        200: {
          content: {
            "application/json": components["schemas"]["PaginatedInvoices"];
          };
        };
      };
    };
  };
  "/disputes": {
    /** List disputes */
    get: {
      parameters: {
        query?: {
          cursor?: string;
        };
      };
      responses: {
        /** @description Paginated disputes */
        200: {
          content: {
            "application/json": components["schemas"]["PaginatedDisputes"];
          };
        };
      };
    };
  };
  "/disputes/{id}/reconcile": {
    /** Reconcile dispute for an invoice */
    post: {
      parameters: {
        path: {
          id: string;
        };
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["ReconcileRequest"];
        };
      };
      responses: {
        /** @description Reconciliation accepted */
        200: {
          content: {
            "application/json": components["schemas"]["ReconcileResponse"];
          };
        };
      };
    };
  };
  "/search": {
    /** Search documents and contracts */
    get: {
      parameters: {
        query: {
          query: string;
        };
      };
      responses: {
        /** @description Search results */
        200: {
          content: {
            "application/json": components["schemas"]["SearchResults"];
          };
        };
      };
    };
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    PaginatedInvoices: {
      items?: components["schemas"]["Invoice"][];
      next_cursor?: string | null;
    };
    Invoice: {
      id?: string;
      tenant_id?: string;
      vendor_id?: string;
      /** @enum {string} */
      status?: "open" | "paid" | "disputed";
      total_amount?: number;
      version?: number;
      /** Format: date-time */
      created_at?: string;
      /** Format: date-time */
      updated_at?: string;
    };
    PaginatedDisputes: {
      items?: components["schemas"]["Dispute"][];
      next_cursor?: string | null;
    };
    Dispute: {
      id?: string;
      invoice_id?: string;
      /** @enum {string} */
      status?: "open" | "reconciling" | "resolved" | "failed";
      reason?: string;
      /** Format: date-time */
      created_at?: string;
    };
    ReconcileRequest: {
      version: number;
    };
    ReconcileResponse: {
      reconcile_key?: string;
      accepted?: boolean;
    };
    SearchResults: {
      query?: string;
      hits?: components["schemas"]["SearchHit"][];
    };
    SearchHit: {
      doc_id?: string;
      /** @enum {string} */
      source?: "contract" | "email" | "purchase_order";
      snippet?: string;
      score?: number;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export type operations = Record<string, never>;
